### ISSUE TITLE
Trigger sync notification doesn't point to correct page

### ISSUE THREAD

**Issue by pvanlaet** [openmotics/gateway-frontend#25]
The `Using our Cloud platform? Don't forget to trigger a sync on the Cloud platform after making changes.` notification does not point to the correct page on the cloud UI but to the dashboard. A typical user will be confused.

Alternatively, is it possible to trigger a cloud sync automatically? If the user uses the cloud UI connection to the cloud is established so I'd guess we can do the sync for him and lose the notification?

**Comment by khenderick** [comment]
The Gateway does not know of the Cloud, not its user or installation ID. So at that point, I can't link to the correct page as it incorporates its ID.

However, I'll keep this open to flag that a sync is required so some automatic process can start a sync.

**Comment by khenderick** [comment]
I consider this as resolved. More recent versions of the gateway can inform the cloud platform that a sync is needed. The frontend will only show the warning on gateways that do not yet have this feature, and since it will be obsolete completely in the future I don't see the need to make the message more specific.
